# Point-LIO Configuration for Unitree L2 (Front)
# Tank tracked vehicle with low CG (229mm)

point_lio:
  ros__parameters:
    # Topics
    lidar_topic: "/lidar_front/pointcloud"
    imu_topic: "/lidar_front/imu"
    
    # Frame IDs
    map_frame: "map"
    lidar_frame: "lidar_front"
    baselink_frame: "base_link"
    
    # Extrinsics: L2 to base_link
    # L2 mounted at nose, ~50cm AGL, level orientation
    # Transform: [x, y, z, roll, pitch, yaw] from base_link to lidar_front
    extrinsic_T: [0.35, 0.0, 0.27]  # 35cm forward, 27cm up from base_link
    extrinsic_R: [1.0, 0.0, 0.0,    # Identity rotation (L2 is level)
                  0.0, 1.0, 0.0,
                  0.0, 0.0, 1.0]
    
    # IMU settings (Unitree L2 built-in 6-axis IMU)
    acc_norm: 9.81  # Gravity (m/s²)
    satu_acc: 16.0  # Accelerometer saturation (m/s²) - estimate, verify from L2 specs
    satu_gyro: 17.5 # Gyroscope saturation (rad/s) - estimate, verify from L2 specs
    
    # Increase if you see saturation warnings on 30° slopes:
    # satu_acc: 20.0
    # satu_gyro: 25.0
    
    # Point cloud processing
    point_filter_num: 1  # Point filter size (1 = no filtering)
    max_iteration: 4     # Max iterations for ICP
    filter_size_surf: 0.5  # Surface feature voxel size (m)
    filter_size_map: 0.5   # Map voxel size (m)
    cube_side_length: 1000.0  # Local map cube size (m)
    
    # Detection range (Unitree L2: 30m @ 90% reflectivity)
    det_range: 80.0  # Detection range for mapping (m)
    
    # Odometry settings
    publish_odometry_without_downsample: false
    max_num_iters: 4
    
    # Mapping settings
    ikdtree_resolution: 0.5  # Resolution of ikd-tree (m)
    
    # Runtime flags
    run_in_offline: false
    pcd_save_enable: false  # Set true to save PCD maps
    pcd_save_interval: -1   # -1 = save at end only
    
    # Output topics (default Point-LIO topics)
    # /point_lio/odom - nav_msgs/Odometry
    # /point_lio/cloud - sensor_msgs/PointCloud2 (registered)
    # /point_lio/path - nav_msgs/Path

